name: Test Workflow

on:
  push:

jobs:
  test:
    runs-on: self-hosted
    steps:  
         - name: Checkout code
           uses: actions/checkout@v4

         - name: Show system info
           run: |
                hostname
                pwd
                whoami
                ls -la
    

         - name: check hostname
           run: hostname

         - name: check current directory
           run: pwd 

         - name: check current user
           run: whoami


              
